# Generated by Django 4.1.4 on 2023-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_comment_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
