# Generated by Django 4.1.4 on 2023-06-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['movie', '-created']},
        ),
    ]
